services:
  api:
    image: 010526282379.dkr.ecr.us-east-1.amazonaws.com/taskmanager-api:${IMAGE_TAG}
    container_name: task-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider 127.0.0.1:3000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  db:
    image: postgres:16
    container_name: taskmanager_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - taskmanager_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  taskmanager_postgres_data:
    external: true